/**
 * models/Blog.js
 * ------------------------------------------------------------
 * Schema and model for blog posts.
 *
 * A blog belongs to one author (User) and optionally one
 * category. It stores the content as sanitised HTML together
 * with SEO metadata, the source (AI-generated or written
 * manually), a publication status and a view counter.
 * ------------------------------------------------------------
 */

const mongoose = require("mongoose");

const blogSchema = new mongoose.Schema(
  {
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    title: { type: String, required: true, trim: true },
    slug: { type: String, required: true, unique: true, index: true },

    // Sanitised HTML article body
    content: { type: String, required: true },
    // Short plain-text summary shown on cards and in meta tags
    excerpt: { type: String, default: "" },
    coverImage: { type: String, default: "" }, // local path, e.g. /uploads/x.jpg

    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
      default: null,
    },

    // SEO fields
    keywords: { type: [String], default: [] },
    metaDescription: { type: String, default: "" },

    // "ai" if generated by Groq, "manual" if written in the editor
    source: { type: String, enum: ["ai", "manual"], default: "manual" },
    // "published" appears on the public site; "draft" is private to the
    // author; "trash" is a soft-deleted state that can be restored.
    status: {
      type: String,
      enum: ["draft", "published", "trash"],
      default: "published",
    },

    views: { type: Number, default: 0 },
  },
  { timestamps: true },
);

module.exports = mongoose.model("Blog", blogSchema);
